npmPublishAccess: public

npmScopes:
  dollarcode:
    npmAlwaysAuth: true
    npmAuthToken: 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

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
